### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by Leandros** [tldr-pages/tldr-c-client#16]
I don't use Windows, neither do I have a valid Windows installation. Would be nice if someone could make `tldr` work natively on Windows.

**Comment by Leandros** [comment]
It does run and compile under MSYS2. However, `libzip` doesn't seem to work (it does not find the file, even though it's there), caching therefore doesn't work.

**Comment by Mic92** [comment]
It also does not recognize windows as a platform yet: https://github.com/tldr-pages/tldr/tree/master/pages/windows

**Comment by MasterOdin** [comment]
This was done in ae5dbdfbec98e1ce0a3c3c244904e2f3cd99510c and part of 1.4.0 release
