### ISSUE TITLE
rename the repo to tldr-c-client

### ISSUE THREAD

**Issue by waldyrious** [tldr-pages/tldr-c-client#20]
to match the documentation

**Comment by Leandros** [comment]
While this would match the documentation, we can't do that unfortunately. It would break all of our past homebrew taps including the core.

**Comment by waldyrious** [comment]
I believe github keep redirects in place, but I'm not sure. If that is the case, would it work?

**Comment by Leandros** [comment]
They keep a redirect in place, but it's undocumented and might break randomly. There is a big red warning when I try to rename the repository.

**Comment by waldyrious** [comment]
I see. That's a pity. I guess the only way to handle this is to create a separate repo and mark this one as deprecated, but that would lose the issue history, and is generally a sub-optimal solution. Feel free to pick what choice seems more appropriate, including closing this issue.

**Comment by isaachier** [comment]
Old issue has an older solution: https://github.com/blog/1508-repository-redirects-are-here

**Comment by zdroid** [comment]
ping @waldyrious @sbrl 

The client is also wrongly stated as C++ client in tldr-pages/tldr's README.

**Comment by sbrl** [comment]
I'd be able to move the repo if we could co-ordinate homebrew.

We should also update the README there then, yeah

**Comment by agnivade** [comment]
I am wondering why this was named cpp client in the first place. Was there C++ code initially, which was replaced with C ?

**Comment by waldyrious** [comment]
> I'd be able to move the repo if we could co-ordinate homebrew.

AFAIK Homebrew [does not support installing old versions of a formula](https://discourse.brew.sh/t/how-to-install-old-version-of-a-formula/654/2) anyway, so we would just need to submit a PR updating the [`tldr` formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/tldr.rb) to match the new repo URL.

**Comment by zdroid** [comment]
@agnivade Seems like your hypothesis is right. https://github.com/tldr-pages/tldr-cpp-client/commit/813c5fb588baf217914006aaed8bb697d7c2d13b#diff-3817fa6a8ba7236b52bad41400452877

**Comment by zdroid** [comment]
@agnivade @sbrl @owenvoke @mebeim Once the repo is renamed, GitHub will automatically redirect old URLs to the new ones. Basically all that's required to be done is to simply rename the repository.

After that related URLs can be changed in https://github.com/Homebrew/homebrew-core/blob/master/Formula/tldr.rb.

**Comment by Leandros** [comment]
> I am wondering why this was named cpp client in the first place. Was there C++ code initially, which was replaced with C ?

Yes, this was originally in C++. I switched it to C at a later point to, eventually, support Windows. Which I never actually got around to implement, unfortunately.

**Comment by sbrl** [comment]
@Leandros: ....but Windows as a C++ compiler?

**Comment by owenvoke** [comment]
I think it's ok to finally close this. 👍 The repo has been renamed, references in Brew have been updated, and everything seems to be working as expected.
