### ISSUE TITLE
disable colors

### ISSUE THREAD

**Issue by t184256** [tldr-pages/tldr-c-client#35]
Please add an option to disable color highlighting (or specify a configurable colorscheme).

**Comment by xuchunyang** [comment]
The color should be disabled **automatically** when the output is not terminal, for example, the color becomes annoying in the following uses:

```sh
tldr ls | less
tldr ls > ls.md
```

Some programs, such as `ls` and `grep`, provides `--color=auto|never|always`.

**Comment by t184256** [comment]
Yes. And I want such an option for `tldr`.
