### ISSUE TITLE
Suggestion: Add an env variable to specify cache directory

### ISSUE THREAD

**Issue by geowarin** [tldr-pages/tldr-c-client#37]
Hello, and thanks for the cli, it's very useful!

Having an env variable like `TLDR_CACHE_DIR` would be very useful to control what's written in the home.

Since it is only a cache, users should expect to be safely able to remove it. 
However, they can be hesitant when it's another dotfile in their home dir.

**Comment by MasterOdin** [comment]
Done in d9453eb07bd69d47ce8cf4c4b8441fe53cff3e7b as part of 1.4.0 release
