### ISSUE TITLE
"tldr --update"  failed due to "Error: Download File: https://github.com/tldr-pages/tldr/archive/master.zip"

### ISSUE THREAD

**Issue by hzfmer** [tldr-pages/tldr-c-client#44]
## Reproduction Rate
<How often could you reproduce this issue, how often do you tried?>
Every time I run `tldr --update`.

## Steps to Reproduce
<Exact steps to reproduce the issue>
Run `tldr -- update`

## Result
<What is the result of this?>

`Error: Downloading File: https://github.com/tldr-pages/tldr/archive/master.zip`
## Expected Result
<What is the expected result?>
Update local database?

## Additional Information
<Which version? Which operating system? Any other information?>

- MacOS High Sierra; used `brew install tldr --HEAD` to install. #38 mentioned install HEAD version can solve this issue, which does work for me.

- I am able to download that `master.zip` file using `wget`.

**Comment by MasterOdin** [comment]
This was fixed in 1.4.0
