### ISSUE TITLE
Error: updating results in error

### ISSUE THREAD

**Issue by gingerbeardman** [tldr-pages/tldr-c-client#61]
## Reproduction Rate
- always

## Steps to Reproduce
tldr -u

## Result
> Error: Could Not Rename: /tmp/tldr4aQHBc/tldr-master to /Volumes/External/Users/matt/.tldrc/tldr-master/

## Expected Result
- should update

## Additional Information
- perhaps related to the master->main branch name change at tldr?

**Comment by unbeatable-101** [comment]
I think the latest version was supposed to fix this, but now it says `Error: Could Not Rename: /tmp/tldr00cE77/tldr to /Users/williamdavis/.tldrc/tldr/`

**Comment by marchersimon** [comment]
@unbeatable-101 this PR sholud fix it.

**Comment by marchersimon** [comment]
I just released the new version, so quickly updating tldr with brew should fix the issue.

**Comment by unbeatable-101** [comment]
Can confirm that it works.
