### ISSUE TITLE
Feature request: auto-update tldr pages

### ISSUE THREAD

**Issue by ds2606** [tldr-pages/tldr-c-client#81]
Every two weeks, I get the message 
`Local data is older than two weeks, use --update to update it.`

I'd like TLDR to just auto-update when it needs to. 

I think this could be easily/simply implemented by giving users the option to set an environment variable, e.g. `TLDR_AUTOUPDATE`. If this variable is set, we could have `check_localdate` automatically call `update_localdb` if necessary. None of this would impact users who do not set the environment variable.

I'd be happy to work on it and submit a PR if people think it's an OK idea.

**Comment by owenvoke** [comment]
Set a cron task to call `tldr --update`?

**Comment by ds2606** [comment]
Yeah that works. I'd rather have the auto-updating be intrinsic to tldr though. If I don't invoke `tldr` for three months, I'd rather `tldr` call an update itself rather than have `cron` query the database every two weeks necessarily. This is minor though and maybe isn't worth the time. I'd still be happy to add the functionality as a side project sometime if folks think it's addable.
